--- # FB Installation Tasks

- name: Add Elastic search Repo into the Repositories LIst
  copy:
    src: files/elastic.repo
    dest: /etc/yum.repos.d/
    owner: root
    group: root
    mode: 0644

- name: Download and Install Filebeat plus other valid Packages
  yum:
    name: "{{pkgs}}"
    state: present

