--- # Setup Unix IDs and Environment Variables and do Permissions right

- name: Ensure group Filebeat exists
  group:
    name: filebeat
    state: present

- name: create Filebeat Unix ID
  user:
    name: filebeat
    shell: /bin/bash
    group: filebeat
    state: present
    create_home: yes
    home: /home/filebeat
  tags: es_unixid

- name: setup the Authorized Key that's relevant for this Cluster
  authorized_key:
    user: filebeat
    state: present
    key: "{{ lookup('file', 'files/KevinInitial.pub') }}"

- name: Set ELASTICSEACH Unix ID's default .bashrc if it's not defined
  copy:
    src: files/default_bashrc
    dest: /home/filebeat/.bashrc
    force: no
  tags: es_unixid



- name: Add Sudoer Permissions to Enable ES as a Service and to Start ES as a Service
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^filebeat ALL='
    line: 'filebeat ALL=(ALL) NOPASSWD: /bin/systemctl daemon-reload, /bin/systemctl enable filebeat.service, /bin/systemctl start filebeat.service'
    validate: '/usr/sbin/visudo -cf %s'
  tags: es_unixid

