--- # Setup services for web server
- hosts: apphosts
  order: sorted
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  tasks:
  - name: Install Httpd on the App Webserver hosts
    yum:
      name: httpd
      state: latest
    notify:
    - startservice
  - name: Install Git client
    yum:
      name: git-core.x86_64
      state: latest
  - name: Install Java 8 JDK
    yum:
      name: java-1.8.0-openjdk.x86_64
      state: latest
  - name: Pre-Condition to manually Downloading the 4.10 Gradle Installer
    file:
      path: /opt/gradle
      state: directory
  - name: Manually Download 4.10 Grade Installer
    get_url:
      url: https://services.gradle.org/distributions/gradle-4.10-bin.zip
      dest: /opt/gradle/gradle-4.10-bin.zip
      checksum: sha256:248cfd92104ce12c5431ddb8309cf713fe58de8e330c63176543320022f59f18
    notify:
    - unpackgradlepackage
  handlers:
  - name: startservice
    service:
      name: httpd
      state: restarted
  - name: unpackgradlepackage
    command: unzip /opt/gradle/gradle-4.10-bin.zip -d /opt/gradle
