--- # Build the ElasticSearch Master Server
- hosts: elasticsearchnode2
  connection: ssh
  remote_user: ansible
  become: yes
  become_method: sudo
  gather_facts: yes

  roles:
    - { role: elasticsearch, es_nodename: node-2 }

  post_tasks:

    - name: Start ES as a Service
      systemd:
        name: elasticsearch
        state: restarted
        daemon_reload: yes
      remote_user: elasticsearch
