--- # Build the Kibana Server
- hosts: beatsservers
  connection: ssh
  remote_user: ansible
  become: yes
  become_method: sudo
  gather_facts: yes

  roles:
    - { role: filebeat }

  post_tasks:
    - name: Start Filebeat as a service
      systemd:
        name: filebeat
        state: restarted
        daemon_reload: yes
        enabled: yes
