--- # Build the ElasticSearch Master Server
- hosts: logstashserver
  connection: ssh
  remote_user: ansible
  become: yes
  become_method: sudo
  gather_facts: yes

  roles:
    - { role: logstash }

  post_tasks:

    - name: Start ES as a Service
      systemd:
        name: elasticsearch
        state: restarted
        daemon_reload: yes
