--- # Build the ElasticSearch Master Server
- hosts: elasticmaster
  connection: ssh
  remote_user: ansible
  become: yes
  become_method: sudo
  gather_facts: yes

  roles:
    - { role: elasticmaster, es_masternodename: node-1 }

  post_tasks:

    - name: Start ES as a Service
      systemd:
        name: elasticsearch
        state: restarted
        daemon_reload: yes
