--- # Master Playbook for Web Server Deployments
- hosts: webservers
  remote_user: ansible
  connection: ssh
  gather_facts: yes
  pre_tasks:
    - name: Start Time
      raw: date > /home/ansible/startofrhelwebserverrole.log

  roles:
    - rhel_webservers

  post_tasks:
    - name: Completed Time
      raw: date > /home/ansible/completionofrhelwebserverrole.log
