--- # Build the Webserver with Apache Webserver and Kibana
- hosts: webservers
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes

  roles:
    - { role: webserver }

  post_tasks:
    - name: Start HTTPD as a service
      systemd:
        name: httpd
        state: restarted
        daemon_reload: yes
        enabled: yes