--- # Common Setup Playbook
- hosts: all
  remote_user: ansible
  connection: ssh
  become_method: sudo
  become: yes
  gather_facts: no
  roles:
    - common

- hosts: webservers
  connection: ssh
  gather_facts: no
  roles:
    - webservers
