--- # Configure the Kibana Installation

- name: Update configuration file kibana.yml.j2 from template
  template:
    src: kibana.yml.j2
    dest: /{{kb_config_home}}/kibana.yml
    owner: kibana
    group: kibana
    mode: 0744