--- # Setup Unix IDs and Environment Variables and do Permissions right

- name: create Kibana Unix ID
  user:
    name: kibana
    shell: /bin/bash
    group: kibana
    state: present
    create_home: yes
    home: /home/kibana

- name: Set kibana Unix ID's default .bashrc if it's not defined
  copy:
    src: files/default_bashrc
    dest: /home/kibana/.bashrc
    force: no

- name: Add Sudoer Permissions to Enable Kibana as a Service and to Start Kibana as a Service
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^kibana ALL='
    line: 'kibana ALL=(ALL) NOPASSWD: /bin/systemctl daemon-reload, /bin/systemctl enable kibana.service, /bin/systemctl start kibana.service'
    validate: '/usr/sbin/visudo -cf %s'