--- # Build Web Server
- name: Download & Install the Httpd Apacahe web server, and mod_ssl and mod_proxy
  yum:
    name: "{{pkgs}}"
    state: latest

- name: Create the Vhosts.d directory
  file:
    path: /etc/httpd/vhost.d
    state: directory
    owner: root
    group: root
    mode: 0644
