--- 
- remote_user: ansible
  become: yes
  become_method: sudo
  - name: Create Pet Business users
    user:
      name: "{{item}}"
      ssh_key_type: rsa
      generate_ssh_key: yes
      state: present
    loop: "{{webserverappusers}}"

# Add SUDO Rules from the common users into the petbusiness users
  
