--- # Main Variable Declarations for the Elastic Master Build
pkgs:
  - httpd
  - mod_ssl.x86_64
  - mod_proxy_html.x86_64
  - git.x86_64
  - java-1.8.0-openjdk.x86_64
  - elasticsearch
elasticsearch:
  clustername: zkdm-cluster
  httpport: 9200
  nodes:
    nodename: "{{ es_nodename }}"
smallvm: True
es_config_home: /etc/elasticsearch
es_home: /usr/share/elasticsearch
#es_nodelist: '"172.31.115.7","172.31.107.55","172.31.105.238"'
es_nodelist:
  - 172.31.115.7
  - 172.31.107.55
  - 172.31.105.238


