--- # Configure the ES Installation

- name: Update configuration file elasticsearch.yml from template
  template:
    src: elasticsearch.yml.j2
    dest: /{{es_config_home}}/elasticsearch.yml
    owner: elasticsearch
    group: elasticsearch
    mode: 0744

- name: Update jvm.options Xms to be able to run on small VMs
  lineinfile:
    path: /{{es_config_home}}/jvm.options
    regexp: '^-Xms'
    state: present
    line: '-Xms500m'
    mode: 0744
    owner: elasticsearch
    group: elasticsearch
  when: smallvm

- name: Update jvm.options Xmx to be able to run on small VMs
  lineinfile:
    path: /{{es_config_home}}/jvm.options
    regexp: '^-Xmx'
    state: present
    line: '-Xmx500m'
    mode: 0744
    owner: elasticsearch
    group: elasticsearch
  when: smallvm
  tags: es_config

- name: Install Discovery EC2 ES Plugin to run ES in AWS EC2 instance
  command: /usr/share/elasticsearch/bin/elasticsearch-plugin install discovery-ec2
