--- # ES Installation Tasks

- name: Add Elastic search Repo into the Repositories LIst
  copy:
    src: files/elasticsearch.repo
    dest: /etc/yum.repos.d/
    owner: root
    group: root
    mode: 0644

- name: Download and Install Elastic Search plus other valid Packages
  yum:
    name: "{{pkgs}}"
    state: present

