--- # Setup Unix IDs and Environment Variables and do Permissions right

- name: create ELASTICSEARCH Unix ID
  user:
    name: elasticsearch
    shell: /bin/bash
    group: elasticsearch
    state: present
    create_home: yes
    home: /home/elasticsearch
  tags: es_unixid

- name: setup the Authorized Key that's relevant for this Cluster
  authorized_key:
    user: elasticsearch
    state: present
    key: "{{ lookup('file', 'files/KevinInitial.pub') }}"

- name: Set ELASTICSEACH Unix ID's default .bashrc if it's not defined
  copy:
    src: files/default_bashrc
    dest: /home/elasticsearch/.bashrc
    force: no
  tags: es_unixid

- name: Update ES_PATH_CONF environment variables for ELASTICSEARCH Unix ID
  lineinfile:
    path: /{{item.homepath}}/.bashrc
    regexp: '^export ES_PATH_CONF'
    line: export ES_PATH_CONF={{es_config_home}}
    mode: 0744
    owner: elasticsearch
    group: elasticsearch
  loop:
    - id: elasticsearch
      homepath: /home/elasticsearch
  tags: es_unixid

- name: Update ES_HOME environment variables for ELASTICSEARCH Unix ID
  lineinfile:
    path: /{{item.homepath}}/.bashrc
    mode: 0744
    regexp: '^export ES_HOME'
    line: |
      export ES_HOME={{es_home}}
      export PATH=${PATH}:${ES_HOME}/bin
    owner: elasticsearch
    group: elasticsearch
  loop:
    - id: elasticsearch
      homepath: /home/elasticsearch
  tags: es_unixid

- name: Add Sudoer Permissions to Enable ES as a Service and to Start ES as a Service
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^elasticsearch ALL='
    line: 'elasticsearch ALL=(ALL) NOPASSWD: /bin/systemctl daemon-reload, /bin/systemctl enable elasticsearch.service, /bin/systemctl start elasticsearch.service'
    validate: '/usr/sbin/visudo -cf %s'
  tags: es_unixid

- name: Ulimits settings for Elasticsearch user
  pam_limits:
    domain: "{{ item.domain }}"
    limit_item: "{{ item.limit }}"
    limit_type: "{{ item.type }}"
    value: "{{ item.value }}"
  loop: "{{ limits }}"
